root@john:/var/www/ustoz# php artisan key:generate
  php artisan storage:link
  php artisan migrate --force
  php artisan db:seed --force
  php artisan config:cache
  php artisan route:cache
  php artisan view:cache


                                                                                  APPLICATION IN PRODUCTION.


 ┌ Are you sure you want to run this command? ──────────────────┐
 │ Yes                                                          │
 └──────────────────────────────────────────────────────────────┘

   INFO  Application key set successfully.


   ERROR  The [public/storage] link already exists.


   INFO  Nothing to migrate.


   INFO  Seeding database.

✅ Admin tayyor: admin@ustoz.uz / admin123
✅ Test o'quvchi tayyor: user@ustoz.uz / password123
✅ Test ustoz yaratildi: ustoz@ustoz.uz / password123
  Database\Seeders\FanSeeder ............................................................................................................... RUNNING

   Illuminate\Database\UniqueConstraintViolationException

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Matematika' for key 'fanlar_nomi_unique' (Connection: mysql, SQL: insert into `fanlar` (`nomi`, `kod`, `rasm`, `tavsif`, `is_active`, `order`, `updated_at`, `created_at`) values (Matematika, MAT, subjects/matematika.png, Algebra, geometriya va matematik tahlil, 1, 1, 2026-03-24 08:48:53, 2026-03-24 08:48:53))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:821
    817▕         // message to include the bindings with SQL, which will make this exception a
    818▕         // lot more helpful to the developer instead of just the database's errors.
    819▕         catch (Exception $e) {
    820▕             if ($this->isUniqueConstraintError($e)) {
  ➜ 821▕                 throw new UniqueConstraintViolationException(
    822▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    823▕                 );
    824▕             }
    825▕

      +17 vendor frames

  18  database/seeders/FanSeeder.php:81
      Illuminate\Database\Eloquent\Model::__callStatic()
      +8 vendor frames

  27  database/seeders/DatabaseSeeder.php:59
      Illuminate\Database\Seeder::call()


   INFO  Configuration cached successfully.


   INFO  Routes cached successfully.



   INFO  Blade templates cached successfully.

root@john:/var/www/ustoz#

